### ISSUE TITLE
how to add new translation?

### ISSUE THREAD

**Issue by ppKrauss** [okfn/opendefinition#132]
The *pt-BR* translation is ok,
  https://github.com/okfn-brasil/opendefinition/blob/gh-pages/od/2.0/pt-br/index.markdown
how to send it to http://opendefinition.org/od/2.0/pt-br ?

PS: the fork was 3 months ago, but only finished now.

**Comment by mlinksva** [comment]
You should be able to send a pull request from your repository to this one, see https://help.github.com/articles/creating-a-pull-request/

If that doesn't work for you let me know.

**Comment by ppKrauss** [comment]
Thanks @mlinksva , the fork was done times ago... Github sends a email,

> The page build completed successfully, but returned the following warning:
> CNAME already taken: opendefinition.org
>  For information on troubleshooting Jekyll see:
>  https://help.github.com/articles/using-jekyll-with-pages#troubleshooting

... so, doesn't work for me.

------
PS:  we are working with od/pt-BR translations 2.0 and 2.1 [here](https://github.com/okfn-brasil/opendefinition/tree/gh-pages/od).  The 2.0 translation is ok, the 2.1 will be fineshed later.

**Comment by mlinksva** [comment]
That error is not relevant to your patch. It's due to the CNAME file containing a domain already being used AND your branch being called gh-pages. The easiest way to not get that error is to rename your branch to something else, say pt-BR-translation. If the branch isn't called gh-pages github won't try to publish a site and run into the error you got notice of. You can still send a pull request in any case.

If not I'll grab your translation when I get a chance in the next day or so. Thanks again!

**Comment by mlinksva** [comment]
Added pt-br 2.0 translation to site.
