### ISSUE TITLE
www & licenses sub domains unavailable

### ISSUE THREAD

**Issue by stuzart** [okfn/opendefinition#181]
Site subhosts 
     http://www.opendefinition.org/
     http://licenses.opendefinition.org/

have become unavailable. In particular the www.opendefinition.org is the root of the URLS defined in JSON file, that points to particular license information - for example http://www.opendefinition.org/licenses/dsl for DSL. (I can't find this JSON file any more, but I think it was provided through the http://licenses.opendefinition.org/ )

Stripping off the 'www' - e.g http://opendefinition.org/licenses/dsl - does work.

Is this a temporary glitch, or should I update my copy of the JSON such that all the opendefinition URLs strip off the www. ?

**Comment by mlinksva** [comment]
Thanks @stuzart for reporting this!

licenses.opendefinition.org does work for me.

I'm not sure what the problem is with www.opendefinition.org so I'm copying @vitorbaptista @serahrono who I believe are OKFN administrators.

It probably makes sense to update the JSON provided regardless, PR to do that at https://github.com/okfn/licenses/pull/75

**Comment by mlinksva** [comment]
Also cc @smth since I see in #183 that you work for OKFN. 😄

**Comment by mlinksva** [comment]
Hey all, I just noticed that www.okfn.org doesn't resolve either!

**Comment by stuzart** [comment]
Thanks for the response. Yes, licenses.opendefinition.org is working again for me, must have been a local issue.
I'll update the JSON we use to correspond to the new updated version from the PR

Thanks

**Comment by mlinksva** [comment]
I'm not sure this was fixed, but `www.` works now. Thanks for reporting!
