### ISSUE TITLE
Maximise should be maximize

### ISSUE THREAD

**Issue by eberlyn** [okfn/opendefinition#196]
"Maximise" is used a lot in this document. It should be spelled "maximize."

**Comment by mik-wright** [comment]
Maximise is the accepted spelling everywhere but the US

**Comment by mlinksva** [comment]
@eberlyn are you looking on a site other than opendefinition.org? The Open Definition itself contains one instance of `maximized` http://opendefinition.org/od/2.1/en/

@mik-wright however z is used in many technical and international settings outside the US; I suppose the Open Definition intentionally or unintentionally has conformed; see https://en.wikipedia.org/wiki/Oxford_spelling

In any case I don't think there is anything to be fixed in this repository, so closing. Thanks!
